### ISSUE TITLE
A question about the tutorial of DLPFC dataset

### ISSUE THREAD

**Issue by JingofGao** [zhoux85/STAligner#5]
I am highly intrigued by your innovative work. The tutorial you shared on the DLPFC dataset only covered the processing of 4 slices. I am curious to know how I can modify the code to incorporate all 12 slices for processing.

**Comment by zhoux85** [comment]
Hi. Since only 403 genes shared after the intersection of top 5000 HVGs of all 12 slices, we suggest you increase the `n_top_genes` to 10000, to ensure enough common HVGs in the combined input matrix. We also used the sample names (not slices) as "batch_name" to simplify the integration order. Tutorial can be found here: https://staligner.readthedocs.io/en/latest/Tutorial_DLPFC_12S.html
